
using Docmino.Domain.Entities;
using Docmino.Domain.Enums;

namespace Docmino.Persistence.SeedData;

public class DocumentSeed
{
    private static readonly DateTime _defaultTime = new(2025, 01, 01);
    public static IEnumerable<Document> Documents => new List<Document>
    {
        new Document
        {
            Id = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
            CreatedAt = new DateTime(2025, 1, 5, 09, 53, 46),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Báo cáo tổng kết công tác năm 2024",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-1",
            CodeNotation = "A-2025-1",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tổng kết công tác năm 2024",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tổng kết công tác năm 2024",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-1",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 1",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("dddddddd-dddd-dddd-dddd-dddddddddddd"),
            CreatedAt = new DateTime(2025, 4, 20, 02, 13, 09),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Kế hoạch triển khai dự án A",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-2",
            CodeNotation = "A-2025-1",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch triển khai dự án A",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch triển khai dự án A",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-2",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 2",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccccc"),
            CreatedAt = new DateTime(2025, 4, 24, 10, 51, 26),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Thông báo nghỉ lễ Tết Nguyên Đán",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-3",
            CodeNotation = "A-2025-1",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo nghỉ lễ Tết Nguyên Đán",
            PageAmount = 5,
            Description = "Mô tả: Thông báo nghỉ lễ Tết Nguyên Đán",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-3",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 3",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
            CreatedAt = new DateTime(2025, 4, 20, 18, 19, 44),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Công văn chỉ đạo phòng chống dịch",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-4",
            CodeNotation = "A-2025-1",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn chỉ đạo phòng chống dịch",
            PageAmount = 5,
            Description = "Mô tả: Công văn chỉ đạo phòng chống dịch",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-4",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 4",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
            CreatedAt = new DateTime(2025, 1, 4, 08, 59, 49),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Biên bản họp đánh giá nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-5",
            CodeNotation = "A-2025-1",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản họp đánh giá nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Biên bản họp đánh giá nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-5",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 5",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("11111111-1111-1111-1111-111111111111"),
            CreatedAt = new DateTime(2025, 4, 21, 15, 30, 50),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Quyết định bổ nhiệm cán bộ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-6",
            CodeNotation = "A-2025-2",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Quyết định bổ nhiệm cán bộ",
            PageAmount = 5,
            Description = "Mô tả: Quyết định bổ nhiệm cán bộ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-6",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 6",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("22222222-2222-2222-2222-222222222222"),
            CreatedAt = new DateTime(2025, 1, 10, 00, 05, 37),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Tờ trình xin ý kiến chỉ đạo",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-7",
            CodeNotation = "A-2025-2",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình xin ý kiến chỉ đạo",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình xin ý kiến chỉ đạo",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-7",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 7",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("ffffffff-ffff-ffff-ffff-ffffffffffff"),
            CreatedAt = new DateTime(2025, 4, 23, 12, 50, 57),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Thông báo tuyển dụng nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-8",
            CodeNotation = "A-2025-2",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo tuyển dụng nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Thông báo tuyển dụng nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-8",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 8",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("33333333-3333-3333-3333-333333333333"),
            CreatedAt = new DateTime(2025, 2, 2, 10, 54, 46),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Công văn yêu cầu báo cáo tiến độ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-9",
            CodeNotation = "A-2025-2",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn yêu cầu báo cáo tiến độ",
            PageAmount = 5,
            Description = "Mô tả: Công văn yêu cầu báo cáo tiến độ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-9",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 9",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("0b1ad12d-4f74-46f1-a5ea-dd197ace0ad0"),
            CreatedAt = new DateTime(2025, 2, 17, 17, 41, 37),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Báo cáo tài chính quý I năm 2025",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-10",
            CodeNotation = "A-2025-2",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tài chính quý I năm 2025",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tài chính quý I năm 2025",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-10",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 10",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("dc8fcfdf-1e19-4555-861e-3cc9ca704874"),
            CreatedAt = new DateTime(2025, 4, 28, 19, 42, 52),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Kế hoạch đào tạo nội bộ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-11",
            CodeNotation = "A-2025-3",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch đào tạo nội bộ",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch đào tạo nội bộ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-11",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 11",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("e0412428-d158-48bb-af2b-dbedbc8eced6"),
            CreatedAt = new DateTime(2025, 2, 28, 16, 02, 40),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Văn bản hướng dẫn thực hiện chính sách",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-12",
            CodeNotation = "A-2025-3",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Văn bản hướng dẫn thực hiện chính sách",
            PageAmount = 5,
            Description = "Mô tả: Văn bản hướng dẫn thực hiện chính sách",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-12",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 12",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("556ff713-ce14-4596-bb6a-3da0e581b006"),
            CreatedAt = new DateTime(2025, 6, 5, 01, 45, 24),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Báo cáo tình hình thực hiện kế hoạch",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-13",
            CodeNotation = "A-2025-3",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tình hình thực hiện kế hoạch",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tình hình thực hiện kế hoạch",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-13",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 13",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("a9b042c9-239c-4cf9-8201-d324697956af"),
            CreatedAt = new DateTime(2025, 1, 18, 08, 46, 27),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Giấy mời họp giao ban tháng",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-14",
            CodeNotation = "A-2025-3",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Giấy mời họp giao ban tháng",
            PageAmount = 5,
            Description = "Mô tả: Giấy mời họp giao ban tháng",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-14",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 14",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("2a47d7f9-17f7-4fef-aa4e-413f2356e249"),
            CreatedAt = new DateTime(2025, 1, 7, 21, 18, 54),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Biên bản nghiệm thu dự án",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-15",
            CodeNotation = "A-2025-3",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản nghiệm thu dự án",
            PageAmount = 5,
            Description = "Mô tả: Biên bản nghiệm thu dự án",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-15",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 15",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("c022676e-d91b-405b-9add-491dfadf6a01"),
            CreatedAt = new DateTime(2025, 5, 9, 06, 33, 52),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Thông báo thay đổi nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-16",
            CodeNotation = "A-2025-4",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo thay đổi nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Thông báo thay đổi nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-16",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 16",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("888c2ff8-c791-44b7-a117-f3d457520f10"),
            CreatedAt = new DateTime(2025, 3, 1, 11, 39, 11),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Văn bản đề xuất mua sắm thiết bị",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-17",
            CodeNotation = "A-2025-4",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Văn bản đề xuất mua sắm thiết bị",
            PageAmount = 5,
            Description = "Mô tả: Văn bản đề xuất mua sắm thiết bị",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-17",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 17",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("24eabcc2-8e22-49d4-aa45-af757dca56a4"),
            CreatedAt = new DateTime(2025, 3, 7, 05, 09, 35),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Công văn gửi các đơn vị trực thuộc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-18",
            CodeNotation = "A-2025-4",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn gửi các đơn vị trực thuộc",
            PageAmount = 5,
            Description = "Mô tả: Công văn gửi các đơn vị trực thuộc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-18",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 18",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("fc630beb-b081-4b1b-aed3-3703614436d3"),
            CreatedAt = new DateTime(2025, 4, 23, 21, 35, 21),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Quyết định xử lý kỷ luật",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-19",
            CodeNotation = "A-2025-4",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Quyết định xử lý kỷ luật",
            PageAmount = 5,
            Description = "Mô tả: Quyết định xử lý kỷ luật",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-19",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 19",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("5ee4f172-1d73-42fb-8c74-8047c18635b7"),
            CreatedAt = new DateTime(2025, 1, 19, 21, 24, 16),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Tờ trình đề nghị hỗ trợ kinh phí",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-20",
            CodeNotation = "A-2025-4",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình đề nghị hỗ trợ kinh phí",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình đề nghị hỗ trợ kinh phí",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-20",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 20",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("5072b563-a1bb-4535-86ac-7b7821b33896"),
            CreatedAt = new DateTime(2025, 1, 3, 22, 55, 24),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Kế hoạch tổ chức sự kiện",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-21",
            CodeNotation = "A-2025-5",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch tổ chức sự kiện",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch tổ chức sự kiện",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-21",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 21",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("a6a1e2b0-5437-4055-85fa-6b5e66c70854"),
            CreatedAt = new DateTime(2025, 1, 1, 22, 49, 45),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Thông báo thay đổi lịch làm việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-22",
            CodeNotation = "A-2025-5",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo thay đổi lịch làm việc",
            PageAmount = 5,
            Description = "Mô tả: Thông báo thay đổi lịch làm việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-22",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 22",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("ce47f3d3-17d7-4b85-b11b-434ed1968fb8"),
            CreatedAt = new DateTime(2025, 4, 28, 03, 40, 19),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Văn bản phân công nhiệm vụ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-23",
            CodeNotation = "A-2025-5",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Văn bản phân công nhiệm vụ",
            PageAmount = 5,
            Description = "Mô tả: Văn bản phân công nhiệm vụ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-23",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 23",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("a4939516-29d3-4780-a767-df2256c6d5a0"),
            CreatedAt = new DateTime(2025, 2, 12, 20, 58, 06),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Báo cáo đánh giá hiệu quả công việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-24",
            CodeNotation = "A-2025-5",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo đánh giá hiệu quả công việc",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo đánh giá hiệu quả công việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-24",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 24",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("524014f5-91a4-4d2d-90ff-a9478795479b"),
            CreatedAt = new DateTime(2025, 2, 21, 00, 12, 40),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Công văn góp ý dự thảo văn bản",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-25",
            CodeNotation = "A-2025-5",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn góp ý dự thảo văn bản",
            PageAmount = 5,
            Description = "Mô tả: Công văn góp ý dự thảo văn bản",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-25",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 25",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("04de90fc-7be6-4e2a-88c1-1fbeca6b2278"),
            CreatedAt = new DateTime(2025, 4, 29, 11, 19, 47),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Biên bản bàn giao tài sản",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-26",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản bàn giao tài sản",
            PageAmount = 5,
            Description = "Mô tả: Biên bản bàn giao tài sản",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-26",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 26",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("b14837de-cb87-46fc-b32b-d62c38d01380"),
            CreatedAt = new DateTime(2025, 3, 9, 16, 18, 52),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Giấy triệu tập họp khẩn",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-27",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Giấy triệu tập họp khẩn",
            PageAmount = 5,
            Description = "Mô tả: Giấy triệu tập họp khẩn",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-27",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 27",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("044abecc-a98a-4f2b-b2d5-ac5ce71b3fad"),
            CreatedAt = new DateTime(2025, 4, 9, 04, 45, 33),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Thông báo thay đổi quy chế",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-28",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo thay đổi quy chế",
            PageAmount = 5,
            Description = "Mô tả: Thông báo thay đổi quy chế",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-28",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 28",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("8a556d4a-0609-4d58-bc4a-8789faf1667b"),
            CreatedAt = new DateTime(2025, 4, 9, 06, 38, 15),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Kế hoạch cải tiến quy trình làm việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-29",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch cải tiến quy trình làm việc",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch cải tiến quy trình làm việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-29",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 29",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("41e40cf4-bcb9-44b0-92b7-df6626472175"),
            CreatedAt = new DateTime(2025, 3, 26, 00, 10, 01),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Tờ trình xin phê duyệt dự án",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber =  "VB-30",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình xin phê duyệt dự án",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình xin phê duyệt dự án",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-30",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 30",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },

        new Document
        {
            Id = Guid.Parse("cfa1f5e8-c045-4dea-9433-53c4243763e4"),
            CreatedAt = new DateTime(2025, 1, 4, 2, 24, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Báo cáo tài chính quý I năm 2025",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-31",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tài chính quý I năm 2025",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tài chính quý I năm 2025",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-31",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 31",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("a08d8d68-2691-4c15-8998-ad932cdda0f7"),
            CreatedAt = new DateTime(2025, 5, 21, 2, 15, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Báo cáo tài chính quý I năm 2025",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-32",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tài chính quý I năm 2025",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tài chính quý I năm 2025",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-32",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 32",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("eadab4eb-a7fa-479a-b598-2066cfb39034"),
            CreatedAt = new DateTime(2025, 1, 30, 16, 29, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Quyết định xử lý kỷ luật",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-33",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Quyết định xử lý kỷ luật",
            PageAmount = 5,
            Description = "Mô tả: Quyết định xử lý kỷ luật",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-33",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 33",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("9d2ddcc6-79f9-46f8-9efe-96995737c3c2"),
            CreatedAt = new DateTime(2025, 3, 20, 7, 2, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Kế hoạch đào tạo nội bộ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-34",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch đào tạo nội bộ",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch đào tạo nội bộ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-34",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 34",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("173e8831-af4d-4b94-b038-96f1a4dcf6b0"),
            CreatedAt = new DateTime(2025, 1, 12, 12, 55, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Công văn chỉ đạo phòng chống dịch",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-35",
            CodeNotation = "A-2025-6",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn chỉ đạo phòng chống dịch",
            PageAmount = 5,
            Description = "Mô tả: Công văn chỉ đạo phòng chống dịch",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-35",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 35",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("8ad9213b-2178-488d-aa58-0fe6cd14ba7a"),
            CreatedAt = new DateTime(2025, 3, 27, 6, 5, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Công văn gửi các đơn vị trực thuộc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-36",
            CodeNotation = "A-2025-7",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn gửi các đơn vị trực thuộc",
            PageAmount = 5,
            Description = "Mô tả: Công văn gửi các đơn vị trực thuộc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-36",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 36",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("8819ee05-3f0e-4bf0-8fcf-d1669568791c"),
            CreatedAt = new DateTime(2025, 1, 14, 8, 11, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Công văn chỉ đạo phòng chống dịch",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-37",
            CodeNotation = "A-2025-7",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn chỉ đạo phòng chống dịch",
            PageAmount = 5,
            Description = "Mô tả: Công văn chỉ đạo phòng chống dịch",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-37",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 37",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("5953b23f-67f2-42e1-be51-c87e95ea13da"),
            CreatedAt = new DateTime(2025, 2, 27, 8, 59, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Kế hoạch tổ chức sự kiện",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-38",
            CodeNotation = "A-2025-7",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch tổ chức sự kiện",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch tổ chức sự kiện",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-38",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 38",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("bb2747ff-9869-4348-87b3-2be85d56da22"),
            CreatedAt = new DateTime(2025, 1, 20, 13, 31, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Quyết định xử lý kỷ luật",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-39",
            CodeNotation = "A-2025-7",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Quyết định xử lý kỷ luật",
            PageAmount = 5,
            Description = "Mô tả: Quyết định xử lý kỷ luật",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-39",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 39",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("30c6bd44-e3c7-4e8b-9d53-37769b28618f"),
            CreatedAt = new DateTime(2025, 5, 15, 2, 55, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Công văn yêu cầu báo cáo tiến độ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-40",
            CodeNotation = "A-2025-7",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn yêu cầu báo cáo tiến độ",
            PageAmount = 5,
            Description = "Mô tả: Công văn yêu cầu báo cáo tiến độ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-40",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 40",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("ab9d21c6-210b-4b30-9505-ba75fdc49e95"),
            CreatedAt = new DateTime(2025, 3, 7, 23, 28, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Văn bản hướng dẫn thực hiện chính sách",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-41",
            CodeNotation = "A-2025-7",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Văn bản hướng dẫn thực hiện chính sách",
            PageAmount = 5,
            Description = "Mô tả: Văn bản hướng dẫn thực hiện chính sách",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-41",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 41",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("ee746cd0-471a-48e8-80fb-a755609ac3a8"),
            CreatedAt = new DateTime(2025, 2, 19, 13, 43, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Báo cáo đánh giá hiệu quả công việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-42",
            CodeNotation = "A-2025-8",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo đánh giá hiệu quả công việc",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo đánh giá hiệu quả công việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-42",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 42",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("08ee2081-8d42-4c10-bdfe-5258abfd5c16"),
            CreatedAt = new DateTime(2025, 2, 22, 6, 50, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Thông báo tuyển dụng nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-43",
            CodeNotation = "A-2025-8",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo tuyển dụng nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Thông báo tuyển dụng nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-43",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 43",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("7b11d983-3557-423b-bfcc-02ca826be1af"),
            CreatedAt = new DateTime(2025, 3, 22, 19, 8, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Kế hoạch cải tiến quy trình làm việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-44",
            CodeNotation = "A-2025-8",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch cải tiến quy trình làm việc",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch cải tiến quy trình làm việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-44",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 44",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("98047b4a-84ad-45fd-b608-497e3d98220a"),
            CreatedAt = new DateTime(2025, 1, 27, 18, 50, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Kế hoạch đào tạo nội bộ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-45",
            CodeNotation = "A-2025-8",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch đào tạo nội bộ",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch đào tạo nội bộ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-45",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 45",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("872d6dcc-629a-44c4-b678-fd8ba90d4690"),
            CreatedAt = new DateTime(2025, 4, 9, 14, 20, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Công văn góp ý dự thảo văn bản",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-46",
            CodeNotation = "A-2025-8",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Công văn góp ý dự thảo văn bản",
            PageAmount = 5,
            Description = "Mô tả: Công văn góp ý dự thảo văn bản",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-46",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 46",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("fc75a507-f3ac-4d6b-8301-b7ec389d097d"),
            CreatedAt = new DateTime(2025, 3, 31, 0, 30, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Thông báo thay đổi lịch làm việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-47",
            CodeNotation = "A-2025-8",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo thay đổi lịch làm việc",
            PageAmount = 5,
            Description = "Mô tả: Thông báo thay đổi lịch làm việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-47",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 47",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("864dde4e-d834-4e44-bdc0-ad1bef8def4c"),
            CreatedAt = new DateTime(2025, 1, 26, 0, 31, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Quyết định bổ nhiệm cán bộ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-48",
            CodeNotation = "A-2025-9",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Quyết định bổ nhiệm cán bộ",
            PageAmount = 5,
            Description = "Mô tả: Quyết định bổ nhiệm cán bộ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-48",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 48",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("645cf45a-d04f-4ab9-974d-a316fe528883"),
            CreatedAt = new DateTime(2025, 4, 7, 6, 16, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Quyết định xử lý kỷ luật",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-49",
            CodeNotation = "A-2025-9",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Quyết định xử lý kỷ luật",
            PageAmount = 5,
            Description = "Mô tả: Quyết định xử lý kỷ luật",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-49",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 49",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("495f3353-c036-41cb-8157-a2055282cce3"),
            CreatedAt = new DateTime(2025, 5, 24, 22, 3, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Tờ trình xin ý kiến chỉ đạo",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-50",
            CodeNotation = "A-2025-9",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình xin ý kiến chỉ đạo",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình xin ý kiến chỉ đạo",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-50",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 50",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("8624ae93-52ed-4f9d-ac3c-394f2bdf4e44"),
            CreatedAt = new DateTime(2025, 1, 24, 12, 19, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Biên bản họp đánh giá nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-51",
            CodeNotation = "A-2025-9",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản họp đánh giá nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Biên bản họp đánh giá nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-51",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 51",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("9a11c885-d321-4107-ac68-a4c2b5596c30"),
            CreatedAt = new DateTime(2025, 1, 12, 16, 52, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Kế hoạch triển khai dự án A",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-52",
            CodeNotation = "A-2025-9",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch triển khai dự án A",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch triển khai dự án A",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-52",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 52",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("6342ed23-36ec-455a-ab3e-65c8c657111b"),
            CreatedAt = new DateTime(2025, 1, 20, 6, 49, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Báo cáo đánh giá hiệu quả công việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-53",
            CodeNotation = "A-2025-9",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo đánh giá hiệu quả công việc",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo đánh giá hiệu quả công việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-53",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 53",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("2881d90e-b622-45ef-ab1b-aa7ef911fd0f"),
            CreatedAt = new DateTime(2025, 4, 4, 14, 47, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Giấy triệu tập họp khẩn",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-54",
            CodeNotation = "A-2025-10",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Giấy triệu tập họp khẩn",
            PageAmount = 5,
            Description = "Mô tả: Giấy triệu tập họp khẩn",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-54",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 54",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("638cd3f6-8172-4127-846d-ff3a9dc6489d"),
            CreatedAt = new DateTime(2025, 4, 11, 3, 39, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Tờ trình xin phê duyệt dự án",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-55",
            CodeNotation = "A-2025-10",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình xin phê duyệt dự án",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình xin phê duyệt dự án",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-55",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 55",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("65eb1e36-6977-4431-84d1-d981dbb29cc2"),
            CreatedAt = new DateTime(2025, 3, 2, 0, 49, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Tờ trình đề nghị hỗ trợ kinh phí",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-56",
            CodeNotation = "A-2025-10",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình đề nghị hỗ trợ kinh phí",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình đề nghị hỗ trợ kinh phí",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-56",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 56",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("681dbce4-31c7-4a76-810f-f9762bcf34b8"),
            CreatedAt = new DateTime(2025, 2, 9, 6, 29, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Báo cáo tổng kết công tác năm 2024",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-57",
            CodeNotation = "A-2025-10",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tổng kết công tác năm 2024",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tổng kết công tác năm 2024",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-57",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 57",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("ccc3a957-7955-4619-9c80-0c813318e29a"),
            CreatedAt = new DateTime(2025, 2, 4, 6, 35, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Thông báo thay đổi nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-58",
            CodeNotation = "A-2025-10",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo thay đổi nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Thông báo thay đổi nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-58",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 58",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("ce541526-60cb-4861-a6de-6deb9f68395e"),
            CreatedAt = new DateTime(2025, 4, 1, 10, 6, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Kế hoạch cải tiến quy trình làm việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-59",
            CodeNotation = "A-2025-10",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch cải tiến quy trình làm việc",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch cải tiến quy trình làm việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-59",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 59",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("624ccf16-1373-4b10-805b-61a8443d9b6d"),
            CreatedAt = new DateTime(2025, 4, 20, 23, 57, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Văn bản hướng dẫn thực hiện chính sách",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-60",
            CodeNotation = "A-2025-11",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Văn bản hướng dẫn thực hiện chính sách",
            PageAmount = 5,
            Description = "Mô tả: Văn bản hướng dẫn thực hiện chính sách",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-60",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 60",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("5fe83d71-c820-44bb-940f-4a8dab57f584"),
            CreatedAt = new DateTime(2025, 6, 3, 18, 37, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Biên bản bàn giao tài sản",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-61",
            CodeNotation = "A-2025-11",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản bàn giao tài sản",
            PageAmount = 5,
            Description = "Mô tả: Biên bản bàn giao tài sản",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-61",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 61",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("a7c0311a-f209-422e-ac53-5d4ab8215d27"),
            CreatedAt = new DateTime(2025, 5, 20, 14, 31, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Báo cáo tình hình thực hiện kế hoạch",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-62",
            CodeNotation = "A-2025-11",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tình hình thực hiện kế hoạch",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tình hình thực hiện kế hoạch",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-62",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 62",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("cb9cfbb5-9450-48ce-946c-888d15f54247"),
            CreatedAt = new DateTime(2025, 5, 28, 8, 36, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Biên bản họp đánh giá nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-63",
            CodeNotation = "A-2025-11",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản họp đánh giá nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Biên bản họp đánh giá nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-63",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 63",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("eddf0044-6949-4104-ac4a-f50dd3e168d1"),
            CreatedAt = new DateTime(2025, 3, 31, 8, 49, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Biên bản nghiệm thu dự án",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-64",
            CodeNotation = "A-2025-11",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản nghiệm thu dự án",
            PageAmount = 5,
            Description = "Mô tả: Biên bản nghiệm thu dự án",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-64",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 64",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("2c4d4d72-4fad-4854-a029-de72684d2367"),
            CreatedAt = new DateTime(2025, 5, 30, 16, 0, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Thông báo nghỉ lễ Tết Nguyên Đán",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-65",
            CodeNotation = "A-2025-11",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo nghỉ lễ Tết Nguyên Đán",
            PageAmount = 5,
            Description = "Mô tả: Thông báo nghỉ lễ Tết Nguyên Đán",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-65",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 65",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("1f7f51b9-dcd1-4628-9c6e-034be3384d83"),
            CreatedAt = new DateTime(2025, 2, 7, 9, 17, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Báo cáo đánh giá hiệu quả công việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-66",
            CodeNotation = "A-2025-12",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo đánh giá hiệu quả công việc",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo đánh giá hiệu quả công việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-66",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 66",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("fbb29d67-b835-4772-9616-23dad7b73227"),
            CreatedAt = new DateTime(2025, 3, 14, 11, 58, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Báo cáo tổng kết công tác năm 2024",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-67",
            CodeNotation = "A-2025-12",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tổng kết công tác năm 2024",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tổng kết công tác năm 2024",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-67",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 67",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("ba4db2b7-c5d4-494b-b166-7ee2e1f9a763"),
            CreatedAt = new DateTime(2025, 5, 13, 14, 55, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Văn bản phân công nhiệm vụ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-68",
            CodeNotation = "A-2025-12",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Văn bản phân công nhiệm vụ",
            PageAmount = 5,
            Description = "Mô tả: Văn bản phân công nhiệm vụ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-68",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 68",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("ba0e46db-9a65-4124-b830-12d326bc1bad"),
            CreatedAt = new DateTime(2025, 4, 9, 12, 49, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Quyết định bổ nhiệm cán bộ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-69",
            CodeNotation = "A-2025-12",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Quyết định bổ nhiệm cán bộ",
            PageAmount = 5,
            Description = "Mô tả: Quyết định bổ nhiệm cán bộ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-69",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 69",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("30f64f16-f6de-468f-9834-cf0f827ec470"),
            CreatedAt = new DateTime(2025, 2, 12, 7, 44, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Kế hoạch cải tiến quy trình làm việc",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-70",
            CodeNotation = "A-2025-12",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch cải tiến quy trình làm việc",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch cải tiến quy trình làm việc",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-70",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 70",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("dfe3223c-48a4-4076-96a8-c3439ac9ae09"),
            CreatedAt = new DateTime(2025, 4, 14, 8, 26, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Thông báo tuyển dụng nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-71",
            CodeNotation = "A-2025-12",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Thông báo tuyển dụng nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Thông báo tuyển dụng nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-71",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 71",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("96703c13-11b4-4a1b-aaab-515026c1f2e1"),
            CreatedAt = new DateTime(2025, 1, 17, 12, 9, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Kế hoạch đào tạo nội bộ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-72",
            CodeNotation = "A-2025-13",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Kế hoạch đào tạo nội bộ",
            PageAmount = 5,
            Description = "Mô tả: Kế hoạch đào tạo nội bộ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-72",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 72",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("547a2ecf-1e4a-46bd-a2b4-01694abaefcf"),
            CreatedAt = new DateTime(2025, 2, 16, 3, 58, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Tờ trình xin phê duyệt dự án",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-73",
            CodeNotation = "A-2025-13",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình xin phê duyệt dự án",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình xin phê duyệt dự án",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-73",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 73",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("fa336e0c-087c-469b-8205-40735fab81ed"),
            CreatedAt = new DateTime(2025, 4, 22, 19, 38, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Tờ trình xin phê duyệt dự án",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-74",
            CodeNotation = "A-2025-13",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình xin phê duyệt dự án",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình xin phê duyệt dự án",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-74",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 74",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("98ca313b-d56c-4599-bba3-460d8d42d4e9"),
            CreatedAt = new DateTime(2025, 5, 10, 16, 51, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Biên bản bàn giao tài sản",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-75",
            CodeNotation = "A-2025-13",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản bàn giao tài sản",
            PageAmount = 5,
            Description = "Mô tả: Biên bản bàn giao tài sản",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-75",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 75",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("821770a9-31f3-4847-99d7-cbf36797dcd8"),
            CreatedAt = new DateTime(2025, 6, 1, 16, 3, 0),
            DocumentRegisterId = Guid.Parse("b1a1c1d1-e1f1-41a1-b1c1-d1e1f1a1b1c1"),
            Name = "Văn bản phân công nhiệm vụ",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-76",
            CodeNotation = "A-2025-13",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Văn bản phân công nhiệm vụ",
            PageAmount = 5,
            Description = "Mô tả: Văn bản phân công nhiệm vụ",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-76",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 76",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("e7670a6a-a133-4ae8-bb0d-10592c0817aa"),
            CreatedAt = new DateTime(2025, 2, 20, 19, 34, 0),
            DocumentRegisterId = Guid.Parse("c2b2d2e2-f2a2-42b2-c2d2-e2f2a2b2c2d2"),
            Name = "Báo cáo tài chính quý I năm 2025",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-77",
            CodeNotation = "A-2025-13",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Báo cáo tài chính quý I năm 2025",
            PageAmount = 5,
            Description = "Mô tả: Báo cáo tài chính quý I năm 2025",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-77",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 77",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("7bfdbf26-22a2-4660-8f02-0a27b86a07c5"),
            CreatedAt = new DateTime(2025, 4, 10, 19, 54, 0),
            DocumentRegisterId = Guid.Parse("d3c3e3f3-a3b3-43c3-d3e3-f3a3b3c3d3e3"),
            Name = "Giấy triệu tập họp khẩn",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-78",
            CodeNotation = "A-2025-14",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Giấy triệu tập họp khẩn",
            PageAmount = 5,
            Description = "Mô tả: Giấy triệu tập họp khẩn",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-78",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 78",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Draff,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("eb95b546-bf5d-47b2-805d-1d5eac93f4e5"),
            CreatedAt = new DateTime(2025, 1, 3, 22, 26, 0),
            DocumentRegisterId = Guid.Parse("e4d4f4a4-b4c4-44d4-e4f4-a4b4c4d4e4f4"),
            Name = "Biên bản họp đánh giá nhân sự",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-79",
            CodeNotation = "A-2025-14",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Biên bản họp đánh giá nhân sự",
            PageAmount = 5,
            Description = "Mô tả: Biên bản họp đánh giá nhân sự",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-79",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 79",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Published,
            StorageId = null
        },
        new Document
        {
            Id = Guid.Parse("e45902d9-7b93-4a64-9633-33039ade86d0"),
            CreatedAt = new DateTime(2025, 3, 31, 16, 26, 0),
            DocumentRegisterId = Guid.Parse("f5e5a5b5-c5d5-45e5-f5a5-b5c5d5e5f5a5"),
            Name = "Tờ trình đề nghị hỗ trợ kinh phí",
            CategoryId = 1,
            FieldId = 1,
            CodeNumber = "VB-80",
            CodeNotation = "A-2025-14",
            IssuedDate = new DateOnly(2025, 1, 1),
            OrganizationId = 1,
            Subject = "Nội dung: Tờ trình đề nghị hỗ trợ kinh phí",
            PageAmount = 5,
            Description = "Mô tả: Tờ trình đề nghị hỗ trợ kinh phí",
            SecurePriority = SecurePriority.Normal,
            UrgentPriority = UrgentPriority.Normal,
            ArrivalNumber = "ĐN-80",
            ArrivalDate = new DateOnly(2025, 1, 2),
            ToPlaces = "Phòng ban 80",
            DueDate = new DateOnly(2025, 1, 15),
            IssuedAmount = 1,
            DocumentStatus = DocumentStatus.Cancel,
            StorageId = null
        },};
}
